//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BLL.Maintenance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.Maintenance.Maintenance")]
    public interface Maintenance {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnLoginrecord", ReplyAction="http://tempuri.org/Maintenance/btnLoginrecordResponse")]
        System.Data.DataSet btnLoginrecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnLoginrecord", ReplyAction="http://tempuri.org/Maintenance/btnLoginrecordResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnLoginrecordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnDeletingLoginRecords", ReplyAction="http://tempuri.org/Maintenance/btnDeletingLoginRecordsResponse")]
        int btnDeletingLoginRecords(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnDeletingLoginRecords", ReplyAction="http://tempuri.org/Maintenance/btnDeletingLoginRecordsResponse")]
        System.Threading.Tasks.Task<int> btnDeletingLoginRecordsAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnQueryaccount", ReplyAction="http://tempuri.org/Maintenance/btnQueryaccountResponse")]
        System.Data.DataSet btnQueryaccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnQueryaccount", ReplyAction="http://tempuri.org/Maintenance/btnQueryaccountResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnQueryaccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnlevel", ReplyAction="http://tempuri.org/Maintenance/btnlevelResponse")]
        System.Data.DataSet btnlevel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnlevel", ReplyAction="http://tempuri.org/Maintenance/btnlevelResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnlevelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btngender", ReplyAction="http://tempuri.org/Maintenance/btngenderResponse")]
        System.Data.DataSet btngender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btngender", ReplyAction="http://tempuri.org/Maintenance/btngenderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btngenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnstate", ReplyAction="http://tempuri.org/Maintenance/btnstateResponse")]
        System.Data.DataSet btnstate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maintenance/btnstate", ReplyAction="http://tempuri.org/Maintenance/btnstateResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnstateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaintenanceChannel : WpfApp.BLL.Maintenance.Maintenance, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaintenanceClient : System.ServiceModel.ClientBase<WpfApp.BLL.Maintenance.Maintenance>, WpfApp.BLL.Maintenance.Maintenance {
        
        public MaintenanceClient() {
        }
        
        public MaintenanceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaintenanceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaintenanceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaintenanceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnLoginrecord() {
            return base.Channel.btnLoginrecord();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnLoginrecordAsync() {
            return base.Channel.btnLoginrecordAsync();
        }
        
        public int btnDeletingLoginRecords(int ID) {
            return base.Channel.btnDeletingLoginRecords(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnDeletingLoginRecordsAsync(int ID) {
            return base.Channel.btnDeletingLoginRecordsAsync(ID);
        }
        
        public System.Data.DataSet btnQueryaccount() {
            return base.Channel.btnQueryaccount();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnQueryaccountAsync() {
            return base.Channel.btnQueryaccountAsync();
        }
        
        public System.Data.DataSet btnlevel() {
            return base.Channel.btnlevel();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnlevelAsync() {
            return base.Channel.btnlevelAsync();
        }
        
        public System.Data.DataSet btngender() {
            return base.Channel.btngender();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btngenderAsync() {
            return base.Channel.btngenderAsync();
        }
        
        public System.Data.DataSet btnstate() {
            return base.Channel.btnstate();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnstateAsync() {
            return base.Channel.btnstateAsync();
        }
    }
}
