//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BLL.Thenurse {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.Thenurse.Thenurse")]
    public interface Thenurse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQuerydata", ReplyAction="http://tempuri.org/Thenurse/btnQuerydataResponse")]
        System.Data.DataSet btnQuerydata();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQuerydata", ReplyAction="http://tempuri.org/Thenurse/btnQuerydataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnQuerydataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/SelectDetailLine", ReplyAction="http://tempuri.org/Thenurse/SelectDetailLineResponse")]
        System.Data.DataSet SelectDetailLine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/SelectDetailLine", ReplyAction="http://tempuri.org/Thenurse/SelectDetailLineResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectDetailLineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnrdata", ReplyAction="http://tempuri.org/Thenurse/btnrdataResponse")]
        System.Data.DataSet btnrdata(int as_departmentK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnrdata", ReplyAction="http://tempuri.org/Thenurse/btnrdataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnrdataAsync(int as_departmentK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/Distributionbed", ReplyAction="http://tempuri.org/Thenurse/DistributionbedResponse")]
        System.Data.DataSet Distributionbed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/Distributionbed", ReplyAction="http://tempuri.org/Thenurse/DistributionbedResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DistributionbedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnempty", ReplyAction="http://tempuri.org/Thenurse/btnemptyResponse")]
        System.Data.DataSet btnempty(int intFid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnempty", ReplyAction="http://tempuri.org/Thenurse/btnemptyResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnemptyAsync(int intFid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnuerydepartment", ReplyAction="http://tempuri.org/Thenurse/btnuerydepartmentResponse")]
        System.Data.DataSet btnuerydepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnuerydepartment", ReplyAction="http://tempuri.org/Thenurse/btnuerydepartmentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnuerydepartmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnsavebeds", ReplyAction="http://tempuri.org/Thenurse/btnsavebedsResponse")]
        int btnsavebeds(int pid, int cbogender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnsavebeds", ReplyAction="http://tempuri.org/Thenurse/btnsavebedsResponse")]
        System.Threading.Tasks.Task<int> btnsavebedsAsync(int pid, int cbogender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnbeds", ReplyAction="http://tempuri.org/Thenurse/btnbedsResponse")]
        int btnbeds(int pid, int cbogender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnbeds", ReplyAction="http://tempuri.org/Thenurse/btnbedsResponse")]
        System.Threading.Tasks.Task<int> btnbedsAsync(int pid, int cbogender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQueryall", ReplyAction="http://tempuri.org/Thenurse/btnQueryallResponse")]
        System.Data.DataSet btnQueryall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQueryall", ReplyAction="http://tempuri.org/Thenurse/btnQueryallResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnQueryallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnemptydisease", ReplyAction="http://tempuri.org/Thenurse/btnemptydiseaseResponse")]
        int btnemptydisease(int cbogender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnemptydisease", ReplyAction="http://tempuri.org/Thenurse/btnemptydiseaseResponse")]
        System.Threading.Tasks.Task<int> btnemptydiseaseAsync(int cbogender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnSpecifyapplication", ReplyAction="http://tempuri.org/Thenurse/btnSpecifyapplicationResponse")]
        System.Data.DataSet btnSpecifyapplication(int Supli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnSpecifyapplication", ReplyAction="http://tempuri.org/Thenurse/btnSpecifyapplicationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSpecifyapplicationAsync(int Supli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQuerylevels", ReplyAction="http://tempuri.org/Thenurse/btnQuerylevelsResponse")]
        System.Data.DataSet btnQuerylevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQuerylevels", ReplyAction="http://tempuri.org/Thenurse/btnQuerylevelsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnQuerylevelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnurgent", ReplyAction="http://tempuri.org/Thenurse/btnurgentResponse")]
        System.Data.DataSet btnurgent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnurgent", ReplyAction="http://tempuri.org/Thenurse/btnurgentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnurgentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQuerycation", ReplyAction="http://tempuri.org/Thenurse/btnQuerycationResponse")]
        System.Data.DataSet btnQuerycation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnQuerycation", ReplyAction="http://tempuri.org/Thenurse/btnQuerycationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnQuerycationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnInformation", ReplyAction="http://tempuri.org/Thenurse/btnInformationResponse")]
        int btnInformation(string Applicatio, int cboSupplies, int Namegood, string txtApplicationdate, string txtapplicant, int cbodepartment, string txtNumberapplications, string Applicationnot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thenurse/btnInformation", ReplyAction="http://tempuri.org/Thenurse/btnInformationResponse")]
        System.Threading.Tasks.Task<int> btnInformationAsync(string Applicatio, int cboSupplies, int Namegood, string txtApplicationdate, string txtapplicant, int cbodepartment, string txtNumberapplications, string Applicationnot);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThenurseChannel : WpfApp.BLL.Thenurse.Thenurse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThenurseClient : System.ServiceModel.ClientBase<WpfApp.BLL.Thenurse.Thenurse>, WpfApp.BLL.Thenurse.Thenurse {
        
        public ThenurseClient() {
        }
        
        public ThenurseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThenurseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThenurseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThenurseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnQuerydata() {
            return base.Channel.btnQuerydata();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnQuerydataAsync() {
            return base.Channel.btnQuerydataAsync();
        }
        
        public System.Data.DataSet SelectDetailLine() {
            return base.Channel.SelectDetailLine();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectDetailLineAsync() {
            return base.Channel.SelectDetailLineAsync();
        }
        
        public System.Data.DataSet btnrdata(int as_departmentK) {
            return base.Channel.btnrdata(as_departmentK);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnrdataAsync(int as_departmentK) {
            return base.Channel.btnrdataAsync(as_departmentK);
        }
        
        public System.Data.DataSet Distributionbed() {
            return base.Channel.Distributionbed();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DistributionbedAsync() {
            return base.Channel.DistributionbedAsync();
        }
        
        public System.Data.DataSet btnempty(int intFid) {
            return base.Channel.btnempty(intFid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnemptyAsync(int intFid) {
            return base.Channel.btnemptyAsync(intFid);
        }
        
        public System.Data.DataSet btnuerydepartment() {
            return base.Channel.btnuerydepartment();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnuerydepartmentAsync() {
            return base.Channel.btnuerydepartmentAsync();
        }
        
        public int btnsavebeds(int pid, int cbogender) {
            return base.Channel.btnsavebeds(pid, cbogender);
        }
        
        public System.Threading.Tasks.Task<int> btnsavebedsAsync(int pid, int cbogender) {
            return base.Channel.btnsavebedsAsync(pid, cbogender);
        }
        
        public int btnbeds(int pid, int cbogender) {
            return base.Channel.btnbeds(pid, cbogender);
        }
        
        public System.Threading.Tasks.Task<int> btnbedsAsync(int pid, int cbogender) {
            return base.Channel.btnbedsAsync(pid, cbogender);
        }
        
        public System.Data.DataSet btnQueryall() {
            return base.Channel.btnQueryall();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnQueryallAsync() {
            return base.Channel.btnQueryallAsync();
        }
        
        public int btnemptydisease(int cbogender) {
            return base.Channel.btnemptydisease(cbogender);
        }
        
        public System.Threading.Tasks.Task<int> btnemptydiseaseAsync(int cbogender) {
            return base.Channel.btnemptydiseaseAsync(cbogender);
        }
        
        public System.Data.DataSet btnSpecifyapplication(int Supli) {
            return base.Channel.btnSpecifyapplication(Supli);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSpecifyapplicationAsync(int Supli) {
            return base.Channel.btnSpecifyapplicationAsync(Supli);
        }
        
        public System.Data.DataSet btnQuerylevels() {
            return base.Channel.btnQuerylevels();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnQuerylevelsAsync() {
            return base.Channel.btnQuerylevelsAsync();
        }
        
        public System.Data.DataSet btnurgent() {
            return base.Channel.btnurgent();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnurgentAsync() {
            return base.Channel.btnurgentAsync();
        }
        
        public System.Data.DataSet btnQuerycation() {
            return base.Channel.btnQuerycation();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnQuerycationAsync() {
            return base.Channel.btnQuerycationAsync();
        }
        
        public int btnInformation(string Applicatio, int cboSupplies, int Namegood, string txtApplicationdate, string txtapplicant, int cbodepartment, string txtNumberapplications, string Applicationnot) {
            return base.Channel.btnInformation(Applicatio, cboSupplies, Namegood, txtApplicationdate, txtapplicant, cbodepartment, txtNumberapplications, Applicationnot);
        }
        
        public System.Threading.Tasks.Task<int> btnInformationAsync(string Applicatio, int cboSupplies, int Namegood, string txtApplicationdate, string txtapplicant, int cbodepartment, string txtNumberapplications, string Applicationnot) {
            return base.Channel.btnInformationAsync(Applicatio, cboSupplies, Namegood, txtApplicationdate, txtapplicant, cbodepartment, txtNumberapplications, Applicationnot);
        }
    }
}
