//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BLL.WDLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.WDLogin.WDLogin")]
    public interface WDLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WDLogin/btnLogin_Click_CheckLogin", ReplyAction="http://tempuri.org/WDLogin/btnLogin_Click_CheckLoginResponse")]
        System.Data.DataSet btnLogin_Click_CheckLogin(string strAccount, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WDLogin/btnLogin_Click_CheckLogin", ReplyAction="http://tempuri.org/WDLogin/btnLogin_Click_CheckLoginResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnLogin_Click_CheckLoginAsync(string strAccount, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WDLogin/Login_record", ReplyAction="http://tempuri.org/WDLogin/Login_recordResponse")]
        int Login_record(string strStaffName, string txt_Account, string permissionGroupName, System.DateTime Time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WDLogin/Login_record", ReplyAction="http://tempuri.org/WDLogin/Login_recordResponse")]
        System.Threading.Tasks.Task<int> Login_recordAsync(string strStaffName, string txt_Account, string permissionGroupName, System.DateTime Time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WDLoginChannel : WpfApp.BLL.WDLogin.WDLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WDLoginClient : System.ServiceModel.ClientBase<WpfApp.BLL.WDLogin.WDLogin>, WpfApp.BLL.WDLogin.WDLogin {
        
        public WDLoginClient() {
        }
        
        public WDLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WDLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WDLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WDLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnLogin_Click_CheckLogin(string strAccount, string strPassword) {
            return base.Channel.btnLogin_Click_CheckLogin(strAccount, strPassword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnLogin_Click_CheckLoginAsync(string strAccount, string strPassword) {
            return base.Channel.btnLogin_Click_CheckLoginAsync(strAccount, strPassword);
        }
        
        public int Login_record(string strStaffName, string txt_Account, string permissionGroupName, System.DateTime Time) {
            return base.Channel.Login_record(strStaffName, txt_Account, permissionGroupName, Time);
        }
        
        public System.Threading.Tasks.Task<int> Login_recordAsync(string strStaffName, string txt_Account, string permissionGroupName, System.DateTime Time) {
            return base.Channel.Login_recordAsync(strStaffName, txt_Account, permissionGroupName, Time);
        }
    }
}
