//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BLL.Assist {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.Assist.Assist")]
    public interface Assist {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnapplication", ReplyAction="http://tempuri.org/Assist/btnapplicationResponse")]
        System.Data.DataSet btnapplication();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnapplication", ReplyAction="http://tempuri.org/Assist/btnapplicationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnapplicationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnmodifyingfor", ReplyAction="http://tempuri.org/Assist/btnmodifyingforResponse")]
        int btnmodifyingfor(int ID, System.DateTime dtpEnterDate, string txtoperation, int cbodisease, string txtreport, string txtAllergic, string txtapplicant, System.DateTime txtTotime, int cboPatients, int cbourgent, int cbobetween);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnmodifyingfor", ReplyAction="http://tempuri.org/Assist/btnmodifyingforResponse")]
        System.Threading.Tasks.Task<int> btnmodifyingforAsync(int ID, System.DateTime dtpEnterDate, string txtoperation, int cbodisease, string txtreport, string txtAllergic, string txtapplicant, System.DateTime txtTotime, int cboPatients, int cbourgent, int cbobetween);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnaudit", ReplyAction="http://tempuri.org/Assist/btnauditResponse")]
        System.Data.DataSet btnaudit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnaudit", ReplyAction="http://tempuri.org/Assist/btnauditResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnauditAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnReview", ReplyAction="http://tempuri.org/Assist/btnReviewResponse")]
        int btnReview(int ID, int cboaudit, string Note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnReview", ReplyAction="http://tempuri.org/Assist/btnReviewResponse")]
        System.Threading.Tasks.Task<int> btnReviewAsync(int ID, int cboaudit, string Note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnDeleteation", ReplyAction="http://tempuri.org/Assist/btnDeleteationResponse")]
        int btnDeleteation(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnDeleteation", ReplyAction="http://tempuri.org/Assist/btnDeleteationResponse")]
        System.Threading.Tasks.Task<int> btnDeleteationAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnapproved", ReplyAction="http://tempuri.org/Assist/btnapprovedResponse")]
        System.Data.DataSet btnapproved();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnapproved", ReplyAction="http://tempuri.org/Assist/btnapprovedResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnapprovedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnAnesthesia", ReplyAction="http://tempuri.org/Assist/btnAnesthesiaResponse")]
        System.Data.DataSet btnAnesthesia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnAnesthesia", ReplyAction="http://tempuri.org/Assist/btnAnesthesiaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnAnesthesiaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnsurgeon", ReplyAction="http://tempuri.org/Assist/btnsurgeonResponse")]
        System.Data.DataSet btnsurgeon(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnsurgeon", ReplyAction="http://tempuri.org/Assist/btnsurgeonResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnsurgeonAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btninformation", ReplyAction="http://tempuri.org/Assist/btninformationResponse")]
        int btninformation(int cbotype, int ID, string txtsurgeon, string txtassistant, string txtassistant2, string txtassistant3, string txtassistant4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btninformation", ReplyAction="http://tempuri.org/Assist/btninformationResponse")]
        System.Threading.Tasks.Task<int> btninformationAsync(int cbotype, int ID, string txtsurgeon, string txtassistant, string txtassistant2, string txtassistant3, string txtassistant4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnongoing", ReplyAction="http://tempuri.org/Assist/btnongoingResponse")]
        int btnongoing(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnongoing", ReplyAction="http://tempuri.org/Assist/btnongoingResponse")]
        System.Threading.Tasks.Task<int> btnongoingAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnended", ReplyAction="http://tempuri.org/Assist/btnendedResponse")]
        int btnended(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnended", ReplyAction="http://tempuri.org/Assist/btnendedResponse")]
        System.Threading.Tasks.Task<int> btnendedAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnQuerycation", ReplyAction="http://tempuri.org/Assist/btnQuerycationResponse")]
        System.Data.DataSet btnQuerycation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnQuerycation", ReplyAction="http://tempuri.org/Assist/btnQuerycationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnQuerycationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnRec", ReplyAction="http://tempuri.org/Assist/btnRecResponse")]
        System.Data.DataSet btnRec();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnRec", ReplyAction="http://tempuri.org/Assist/btnRecResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnRecAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnclassification", ReplyAction="http://tempuri.org/Assist/btnclassificationResponse")]
        System.Data.DataSet btnclassification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnclassification", ReplyAction="http://tempuri.org/Assist/btnclassificationResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnclassificationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnMaterialinput", ReplyAction="http://tempuri.org/Assist/btnMaterialinputResponse")]
        int btnMaterialinput(string Namegood, int Enternumbe, decimal Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnMaterialinput", ReplyAction="http://tempuri.org/Assist/btnMaterialinputResponse")]
        System.Threading.Tasks.Task<int> btnMaterialinputAsync(string Namegood, int Enternumbe, decimal Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnSuppliesquery", ReplyAction="http://tempuri.org/Assist/btnSuppliesqueryResponse")]
        System.Data.DataSet btnSuppliesquery();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnSuppliesquery", ReplyAction="http://tempuri.org/Assist/btnSuppliesqueryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSuppliesqueryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnSuppliesdelete", ReplyAction="http://tempuri.org/Assist/btnSuppliesdeleteResponse")]
        int btnSuppliesdelete(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnSuppliesdelete", ReplyAction="http://tempuri.org/Assist/btnSuppliesdeleteResponse")]
        System.Threading.Tasks.Task<int> btnSuppliesdeleteAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnModifygoods", ReplyAction="http://tempuri.org/Assist/btnModifygoodsResponse")]
        int btnModifygoods(string Namegood, int Enternumbe, double Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnModifygoods", ReplyAction="http://tempuri.org/Assist/btnModifygoodsResponse")]
        System.Threading.Tasks.Task<int> btnModifygoodsAsync(string Namegood, int Enternumbe, double Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnApp", ReplyAction="http://tempuri.org/Assist/btnAppResponse")]
        System.Data.DataSet btnApp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnApp", ReplyAction="http://tempuri.org/Assist/btnAppResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnAppAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnauditing", ReplyAction="http://tempuri.org/Assist/btnauditingResponse")]
        int btnauditing(int ID, int cboApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnauditing", ReplyAction="http://tempuri.org/Assist/btnauditingResponse")]
        System.Threading.Tasks.Task<int> btnauditingAsync(int ID, int cboApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnSdelete", ReplyAction="http://tempuri.org/Assist/btnSdeleteResponse")]
        int btnSdelete(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnSdelete", ReplyAction="http://tempuri.org/Assist/btnSdeleteResponse")]
        System.Threading.Tasks.Task<int> btnSdeleteAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnRecipients", ReplyAction="http://tempuri.org/Assist/btnRecipientsResponse")]
        int btnRecipients(int Then, int IntB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnRecipients", ReplyAction="http://tempuri.org/Assist/btnRecipientsResponse")]
        System.Threading.Tasks.Task<int> btnRecipientsAsync(int Then, int IntB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnmedicine", ReplyAction="http://tempuri.org/Assist/btnmedicineResponse")]
        int btnmedicine(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Assist/btnmedicine", ReplyAction="http://tempuri.org/Assist/btnmedicineResponse")]
        System.Threading.Tasks.Task<int> btnmedicineAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AssistChannel : WpfApp.BLL.Assist.Assist, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssistClient : System.ServiceModel.ClientBase<WpfApp.BLL.Assist.Assist>, WpfApp.BLL.Assist.Assist {
        
        public AssistClient() {
        }
        
        public AssistClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssistClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssistClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssistClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnapplication() {
            return base.Channel.btnapplication();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnapplicationAsync() {
            return base.Channel.btnapplicationAsync();
        }
        
        public int btnmodifyingfor(int ID, System.DateTime dtpEnterDate, string txtoperation, int cbodisease, string txtreport, string txtAllergic, string txtapplicant, System.DateTime txtTotime, int cboPatients, int cbourgent, int cbobetween) {
            return base.Channel.btnmodifyingfor(ID, dtpEnterDate, txtoperation, cbodisease, txtreport, txtAllergic, txtapplicant, txtTotime, cboPatients, cbourgent, cbobetween);
        }
        
        public System.Threading.Tasks.Task<int> btnmodifyingforAsync(int ID, System.DateTime dtpEnterDate, string txtoperation, int cbodisease, string txtreport, string txtAllergic, string txtapplicant, System.DateTime txtTotime, int cboPatients, int cbourgent, int cbobetween) {
            return base.Channel.btnmodifyingforAsync(ID, dtpEnterDate, txtoperation, cbodisease, txtreport, txtAllergic, txtapplicant, txtTotime, cboPatients, cbourgent, cbobetween);
        }
        
        public System.Data.DataSet btnaudit() {
            return base.Channel.btnaudit();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnauditAsync() {
            return base.Channel.btnauditAsync();
        }
        
        public int btnReview(int ID, int cboaudit, string Note) {
            return base.Channel.btnReview(ID, cboaudit, Note);
        }
        
        public System.Threading.Tasks.Task<int> btnReviewAsync(int ID, int cboaudit, string Note) {
            return base.Channel.btnReviewAsync(ID, cboaudit, Note);
        }
        
        public int btnDeleteation(int ID) {
            return base.Channel.btnDeleteation(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnDeleteationAsync(int ID) {
            return base.Channel.btnDeleteationAsync(ID);
        }
        
        public System.Data.DataSet btnapproved() {
            return base.Channel.btnapproved();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnapprovedAsync() {
            return base.Channel.btnapprovedAsync();
        }
        
        public System.Data.DataSet btnAnesthesia() {
            return base.Channel.btnAnesthesia();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnAnesthesiaAsync() {
            return base.Channel.btnAnesthesiaAsync();
        }
        
        public System.Data.DataSet btnsurgeon(int ID) {
            return base.Channel.btnsurgeon(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnsurgeonAsync(int ID) {
            return base.Channel.btnsurgeonAsync(ID);
        }
        
        public int btninformation(int cbotype, int ID, string txtsurgeon, string txtassistant, string txtassistant2, string txtassistant3, string txtassistant4) {
            return base.Channel.btninformation(cbotype, ID, txtsurgeon, txtassistant, txtassistant2, txtassistant3, txtassistant4);
        }
        
        public System.Threading.Tasks.Task<int> btninformationAsync(int cbotype, int ID, string txtsurgeon, string txtassistant, string txtassistant2, string txtassistant3, string txtassistant4) {
            return base.Channel.btninformationAsync(cbotype, ID, txtsurgeon, txtassistant, txtassistant2, txtassistant3, txtassistant4);
        }
        
        public int btnongoing(int ID) {
            return base.Channel.btnongoing(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnongoingAsync(int ID) {
            return base.Channel.btnongoingAsync(ID);
        }
        
        public int btnended(int ID) {
            return base.Channel.btnended(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnendedAsync(int ID) {
            return base.Channel.btnendedAsync(ID);
        }
        
        public System.Data.DataSet btnQuerycation() {
            return base.Channel.btnQuerycation();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnQuerycationAsync() {
            return base.Channel.btnQuerycationAsync();
        }
        
        public System.Data.DataSet btnRec() {
            return base.Channel.btnRec();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnRecAsync() {
            return base.Channel.btnRecAsync();
        }
        
        public System.Data.DataSet btnclassification() {
            return base.Channel.btnclassification();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnclassificationAsync() {
            return base.Channel.btnclassificationAsync();
        }
        
        public int btnMaterialinput(string Namegood, int Enternumbe, decimal Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot) {
            return base.Channel.btnMaterialinput(Namegood, Enternumbe, Thepric, Suppliescategor, Generatethedat, Expirationdat, Barcod, Expirationdata, Drugnot);
        }
        
        public System.Threading.Tasks.Task<int> btnMaterialinputAsync(string Namegood, int Enternumbe, decimal Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot) {
            return base.Channel.btnMaterialinputAsync(Namegood, Enternumbe, Thepric, Suppliescategor, Generatethedat, Expirationdat, Barcod, Expirationdata, Drugnot);
        }
        
        public System.Data.DataSet btnSuppliesquery() {
            return base.Channel.btnSuppliesquery();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSuppliesqueryAsync() {
            return base.Channel.btnSuppliesqueryAsync();
        }
        
        public int btnSuppliesdelete(int ID) {
            return base.Channel.btnSuppliesdelete(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnSuppliesdeleteAsync(int ID) {
            return base.Channel.btnSuppliesdeleteAsync(ID);
        }
        
        public int btnModifygoods(string Namegood, int Enternumbe, double Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot, int ID) {
            return base.Channel.btnModifygoods(Namegood, Enternumbe, Thepric, Suppliescategor, Generatethedat, Expirationdat, Barcod, Expirationdata, Drugnot, ID);
        }
        
        public System.Threading.Tasks.Task<int> btnModifygoodsAsync(string Namegood, int Enternumbe, double Thepric, int Suppliescategor, string Generatethedat, string Expirationdat, string Barcod, string Expirationdata, string Drugnot, int ID) {
            return base.Channel.btnModifygoodsAsync(Namegood, Enternumbe, Thepric, Suppliescategor, Generatethedat, Expirationdat, Barcod, Expirationdata, Drugnot, ID);
        }
        
        public System.Data.DataSet btnApp() {
            return base.Channel.btnApp();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnAppAsync() {
            return base.Channel.btnAppAsync();
        }
        
        public int btnauditing(int ID, int cboApplication) {
            return base.Channel.btnauditing(ID, cboApplication);
        }
        
        public System.Threading.Tasks.Task<int> btnauditingAsync(int ID, int cboApplication) {
            return base.Channel.btnauditingAsync(ID, cboApplication);
        }
        
        public int btnSdelete(int ID) {
            return base.Channel.btnSdelete(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnSdeleteAsync(int ID) {
            return base.Channel.btnSdeleteAsync(ID);
        }
        
        public int btnRecipients(int Then, int IntB) {
            return base.Channel.btnRecipients(Then, IntB);
        }
        
        public System.Threading.Tasks.Task<int> btnRecipientsAsync(int Then, int IntB) {
            return base.Channel.btnRecipientsAsync(Then, IntB);
        }
        
        public int btnmedicine(int ID) {
            return base.Channel.btnmedicine(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnmedicineAsync(int ID) {
            return base.Channel.btnmedicineAsync(ID);
        }
    }
}
