//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BLL.Management {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.Management.Management")]
    public interface Management {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/bynQuerydrugs", ReplyAction="http://tempuri.org/Management/bynQuerydrugsResponse")]
        System.Data.DataSet bynQuerydrugs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/bynQuerydrugs", ReplyAction="http://tempuri.org/Management/bynQuerydrugsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> bynQuerydrugsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnCTraditional", ReplyAction="http://tempuri.org/Management/btnCTraditionalResponse")]
        System.Data.DataSet btnCTraditional();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnCTraditional", ReplyAction="http://tempuri.org/Management/btnCTraditionalResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnCTraditionalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnDrugtype", ReplyAction="http://tempuri.org/Management/btnDrugtypeResponse")]
        System.Data.DataSet btnDrugtype();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnDrugtype", ReplyAction="http://tempuri.org/Management/btnDrugtypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnDrugtypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btn_Cedicine", ReplyAction="http://tempuri.org/Management/btn_CedicineResponse")]
        int btn_Cedicine(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btn_Cedicine", ReplyAction="http://tempuri.org/Management/btn_CedicineResponse")]
        System.Threading.Tasks.Task<int> btn_CedicineAsync(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btn_western", ReplyAction="http://tempuri.org/Management/btn_westernResponse")]
        int btn_western(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btn_western", ReplyAction="http://tempuri.org/Management/btn_westernResponse")]
        System.Threading.Tasks.Task<int> btn_westernAsync(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnDeleteComd", ReplyAction="http://tempuri.org/Management/btnDeleteComdResponse")]
        int btnDeleteComd(int IDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnDeleteComd", ReplyAction="http://tempuri.org/Management/btnDeleteComdResponse")]
        System.Threading.Tasks.Task<int> btnDeleteComdAsync(int IDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnDeletCedcine", ReplyAction="http://tempuri.org/Management/btnDeletCedcineResponse")]
        int btnDeletCedcine(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnDeletCedcine", ReplyAction="http://tempuri.org/Management/btnDeletCedcineResponse")]
        System.Threading.Tasks.Task<int> btnDeletCedcineAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btntraditionalChid", ReplyAction="http://tempuri.org/Management/btntraditionalChidResponse")]
        int btntraditionalChid(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btntraditionalChid", ReplyAction="http://tempuri.org/Management/btntraditionalChidResponse")]
        System.Threading.Tasks.Task<int> btntraditionalChidAsync(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnWestern", ReplyAction="http://tempuri.org/Management/btnWesternResponse")]
        int btnWestern(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnWestern", ReplyAction="http://tempuri.org/Management/btnWesternResponse")]
        System.Threading.Tasks.Task<int> btnWesternAsync(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnSinglereceive", ReplyAction="http://tempuri.org/Management/btnSinglereceiveResponse")]
        int btnSinglereceive(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnSinglereceive", ReplyAction="http://tempuri.org/Management/btnSinglereceiveResponse")]
        System.Threading.Tasks.Task<int> btnSinglereceiveAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnAllreceive", ReplyAction="http://tempuri.org/Management/btnAllreceiveResponse")]
        int btnAllreceive(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnAllreceive", ReplyAction="http://tempuri.org/Management/btnAllreceiveResponse")]
        System.Threading.Tasks.Task<int> btnAllreceiveAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnnumberof", ReplyAction="http://tempuri.org/Management/btnnumberofResponse")]
        System.Data.DataSet btnnumberof();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnnumberof", ReplyAction="http://tempuri.org/Management/btnnumberofResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnnumberofAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btncalculation", ReplyAction="http://tempuri.org/Management/btncalculationResponse")]
        int btncalculation(int ID, int JG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btncalculation", ReplyAction="http://tempuri.org/Management/btncalculationResponse")]
        System.Threading.Tasks.Task<int> btncalculationAsync(int ID, int JG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnprocessing", ReplyAction="http://tempuri.org/Management/btnprocessingResponse")]
        int btnprocessing(int UID, string Note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Management/btnprocessing", ReplyAction="http://tempuri.org/Management/btnprocessingResponse")]
        System.Threading.Tasks.Task<int> btnprocessingAsync(int UID, string Note);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManagementChannel : WpfApp.BLL.Management.Management, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagementClient : System.ServiceModel.ClientBase<WpfApp.BLL.Management.Management>, WpfApp.BLL.Management.Management {
        
        public ManagementClient() {
        }
        
        public ManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet bynQuerydrugs() {
            return base.Channel.bynQuerydrugs();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> bynQuerydrugsAsync() {
            return base.Channel.bynQuerydrugsAsync();
        }
        
        public System.Data.DataSet btnCTraditional() {
            return base.Channel.btnCTraditional();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnCTraditionalAsync() {
            return base.Channel.btnCTraditionalAsync();
        }
        
        public System.Data.DataSet btnDrugtype() {
            return base.Channel.btnDrugtype();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnDrugtypeAsync() {
            return base.Channel.btnDrugtypeAsync();
        }
        
        public int btn_Cedicine(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btn_Cedicine(cbo_Sup, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public System.Threading.Tasks.Task<int> btn_CedicineAsync(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btn_CedicineAsync(cbo_Sup, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public int btn_western(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btn_western(cbo_Sup, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public System.Threading.Tasks.Task<int> btn_westernAsync(int cbo_Sup, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btn_westernAsync(cbo_Sup, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public int btnDeleteComd(int IDC) {
            return base.Channel.btnDeleteComd(IDC);
        }
        
        public System.Threading.Tasks.Task<int> btnDeleteComdAsync(int IDC) {
            return base.Channel.btnDeleteComdAsync(IDC);
        }
        
        public int btnDeletCedcine(int ID) {
            return base.Channel.btnDeletCedcine(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnDeletCedcineAsync(int ID) {
            return base.Channel.btnDeletCedcineAsync(ID);
        }
        
        public int btntraditionalChid(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btntraditionalChid(ID, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public System.Threading.Tasks.Task<int> btntraditionalChidAsync(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btntraditionalChidAsync(ID, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public int btnWestern(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btnWestern(ID, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public System.Threading.Tasks.Task<int> btnWesternAsync(int ID, string txtDrugnumber, string txtTheprice, string txtEnternumber, string txtDrugname, string txtGeneratethedate, string txtQualitytime, string txtProductionaddress, string txtspecifications) {
            return base.Channel.btnWesternAsync(ID, txtDrugnumber, txtTheprice, txtEnternumber, txtDrugname, txtGeneratethedate, txtQualitytime, txtProductionaddress, txtspecifications);
        }
        
        public int btnSinglereceive(int ID) {
            return base.Channel.btnSinglereceive(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnSinglereceiveAsync(int ID) {
            return base.Channel.btnSinglereceiveAsync(ID);
        }
        
        public int btnAllreceive(int ID) {
            return base.Channel.btnAllreceive(ID);
        }
        
        public System.Threading.Tasks.Task<int> btnAllreceiveAsync(int ID) {
            return base.Channel.btnAllreceiveAsync(ID);
        }
        
        public System.Data.DataSet btnnumberof() {
            return base.Channel.btnnumberof();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnnumberofAsync() {
            return base.Channel.btnnumberofAsync();
        }
        
        public int btncalculation(int ID, int JG) {
            return base.Channel.btncalculation(ID, JG);
        }
        
        public System.Threading.Tasks.Task<int> btncalculationAsync(int ID, int JG) {
            return base.Channel.btncalculationAsync(ID, JG);
        }
        
        public int btnprocessing(int UID, string Note) {
            return base.Channel.btnprocessing(UID, Note);
        }
        
        public System.Threading.Tasks.Task<int> btnprocessingAsync(int UID, string Note) {
            return base.Channel.btnprocessingAsync(UID, Note);
        }
    }
}
