//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.BLL.ChuRuYuan {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.ChuRuYuan.ChuRuYuan")]
    public interface ChuRuYuan {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/btnQuerydata", ReplyAction="http://tempuri.org/ChuRuYuan/btnQuerydataResponse")]
        System.Data.DataSet btnQuerydata();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/btnQuerydata", ReplyAction="http://tempuri.org/ChuRuYuan/btnQuerydataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnQuerydataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/logintime", ReplyAction="http://tempuri.org/ChuRuYuan/logintimeResponse")]
        System.Data.DataSet logintime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/logintime", ReplyAction="http://tempuri.org/ChuRuYuan/logintimeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> logintimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/SelectGender", ReplyAction="http://tempuri.org/ChuRuYuan/SelectGenderResponse")]
        System.Data.DataSet SelectGender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/SelectGender", ReplyAction="http://tempuri.org/ChuRuYuan/SelectGenderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectGenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/department", ReplyAction="http://tempuri.org/ChuRuYuan/departmentResponse")]
        System.Data.DataSet department();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/department", ReplyAction="http://tempuri.org/ChuRuYuan/departmentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> departmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/InsertStaff", ReplyAction="http://tempuri.org/ChuRuYuan/InsertStaffResponse")]
        int InsertStaff(
                    int cbo_PostSelectionChanged, 
                    int cbogender, 
                    string txtNumber, 
                    string txtName, 
                    string cboStaffType, 
                    string txtPhoneNumber, 
                    string cboWork, 
                    string txtidCar, 
                    System.DateTime dtmbirth, 
                    string txtAge, 
                    System.DateTime dtmentry_date, 
                    string txtAddress, 
                    string txtNote, 
                    int Bloodtype, 
                    int Drugallergy, 
                    string Emergencycontact, 
                    string Emergencynumber, 
                    string Homeaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/InsertStaff", ReplyAction="http://tempuri.org/ChuRuYuan/InsertStaffResponse")]
        System.Threading.Tasks.Task<int> InsertStaffAsync(
                    int cbo_PostSelectionChanged, 
                    int cbogender, 
                    string txtNumber, 
                    string txtName, 
                    string cboStaffType, 
                    string txtPhoneNumber, 
                    string cboWork, 
                    string txtidCar, 
                    System.DateTime dtmbirth, 
                    string txtAge, 
                    System.DateTime dtmentry_date, 
                    string txtAddress, 
                    string txtNote, 
                    int Bloodtype, 
                    int Drugallergy, 
                    string Emergencycontact, 
                    string Emergencynumber, 
                    string Homeaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/Delete", ReplyAction="http://tempuri.org/ChuRuYuan/DeleteResponse")]
        int Delete(int patientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/Delete", ReplyAction="http://tempuri.org/ChuRuYuan/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int patientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/Modifythedata", ReplyAction="http://tempuri.org/ChuRuYuan/ModifythedataResponse")]
        int Modifythedata(int ID, int cbo_PostSelectionChanged, int cbogender, string txtNumber, string txtName, string cboStaffType, string txtPhoneNumber, string cboWork, string txtidCar, System.DateTime dtmbirth, string txtAge, System.DateTime dtmentry_date, string txtAddress, string txtNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/Modifythedata", ReplyAction="http://tempuri.org/ChuRuYuan/ModifythedataResponse")]
        System.Threading.Tasks.Task<int> ModifythedataAsync(int ID, int cbo_PostSelectionChanged, int cbogender, string txtNumber, string txtName, string cboStaffType, string txtPhoneNumber, string cboWork, string txtidCar, System.DateTime dtmbirth, string txtAge, System.DateTime dtmentry_date, string txtAddress, string txtNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/btnBlood", ReplyAction="http://tempuri.org/ChuRuYuan/btnBloodResponse")]
        System.Data.DataSet btnBlood();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/btnBlood", ReplyAction="http://tempuri.org/ChuRuYuan/btnBloodResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnBloodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/btnAllergic", ReplyAction="http://tempuri.org/ChuRuYuan/btnAllergicResponse")]
        System.Data.DataSet btnAllergic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuRuYuan/btnAllergic", ReplyAction="http://tempuri.org/ChuRuYuan/btnAllergicResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnAllergicAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChuRuYuanChannel : WpfApp.BLL.ChuRuYuan.ChuRuYuan, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChuRuYuanClient : System.ServiceModel.ClientBase<WpfApp.BLL.ChuRuYuan.ChuRuYuan>, WpfApp.BLL.ChuRuYuan.ChuRuYuan {
        
        public ChuRuYuanClient() {
        }
        
        public ChuRuYuanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChuRuYuanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChuRuYuanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChuRuYuanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnQuerydata() {
            return base.Channel.btnQuerydata();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnQuerydataAsync() {
            return base.Channel.btnQuerydataAsync();
        }
        
        public System.Data.DataSet logintime() {
            return base.Channel.logintime();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> logintimeAsync() {
            return base.Channel.logintimeAsync();
        }
        
        public System.Data.DataSet SelectGender() {
            return base.Channel.SelectGender();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectGenderAsync() {
            return base.Channel.SelectGenderAsync();
        }
        
        public System.Data.DataSet department() {
            return base.Channel.department();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> departmentAsync() {
            return base.Channel.departmentAsync();
        }
        
        public int InsertStaff(
                    int cbo_PostSelectionChanged, 
                    int cbogender, 
                    string txtNumber, 
                    string txtName, 
                    string cboStaffType, 
                    string txtPhoneNumber, 
                    string cboWork, 
                    string txtidCar, 
                    System.DateTime dtmbirth, 
                    string txtAge, 
                    System.DateTime dtmentry_date, 
                    string txtAddress, 
                    string txtNote, 
                    int Bloodtype, 
                    int Drugallergy, 
                    string Emergencycontact, 
                    string Emergencynumber, 
                    string Homeaddress) {
            return base.Channel.InsertStaff(cbo_PostSelectionChanged, cbogender, txtNumber, txtName, cboStaffType, txtPhoneNumber, cboWork, txtidCar, dtmbirth, txtAge, dtmentry_date, txtAddress, txtNote, Bloodtype, Drugallergy, Emergencycontact, Emergencynumber, Homeaddress);
        }
        
        public System.Threading.Tasks.Task<int> InsertStaffAsync(
                    int cbo_PostSelectionChanged, 
                    int cbogender, 
                    string txtNumber, 
                    string txtName, 
                    string cboStaffType, 
                    string txtPhoneNumber, 
                    string cboWork, 
                    string txtidCar, 
                    System.DateTime dtmbirth, 
                    string txtAge, 
                    System.DateTime dtmentry_date, 
                    string txtAddress, 
                    string txtNote, 
                    int Bloodtype, 
                    int Drugallergy, 
                    string Emergencycontact, 
                    string Emergencynumber, 
                    string Homeaddress) {
            return base.Channel.InsertStaffAsync(cbo_PostSelectionChanged, cbogender, txtNumber, txtName, cboStaffType, txtPhoneNumber, cboWork, txtidCar, dtmbirth, txtAge, dtmentry_date, txtAddress, txtNote, Bloodtype, Drugallergy, Emergencycontact, Emergencynumber, Homeaddress);
        }
        
        public int Delete(int patientID) {
            return base.Channel.Delete(patientID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int patientID) {
            return base.Channel.DeleteAsync(patientID);
        }
        
        public int Modifythedata(int ID, int cbo_PostSelectionChanged, int cbogender, string txtNumber, string txtName, string cboStaffType, string txtPhoneNumber, string cboWork, string txtidCar, System.DateTime dtmbirth, string txtAge, System.DateTime dtmentry_date, string txtAddress, string txtNote) {
            return base.Channel.Modifythedata(ID, cbo_PostSelectionChanged, cbogender, txtNumber, txtName, cboStaffType, txtPhoneNumber, cboWork, txtidCar, dtmbirth, txtAge, dtmentry_date, txtAddress, txtNote);
        }
        
        public System.Threading.Tasks.Task<int> ModifythedataAsync(int ID, int cbo_PostSelectionChanged, int cbogender, string txtNumber, string txtName, string cboStaffType, string txtPhoneNumber, string cboWork, string txtidCar, System.DateTime dtmbirth, string txtAge, System.DateTime dtmentry_date, string txtAddress, string txtNote) {
            return base.Channel.ModifythedataAsync(ID, cbo_PostSelectionChanged, cbogender, txtNumber, txtName, cboStaffType, txtPhoneNumber, cboWork, txtidCar, dtmbirth, txtAge, dtmentry_date, txtAddress, txtNote);
        }
        
        public System.Data.DataSet btnBlood() {
            return base.Channel.btnBlood();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnBloodAsync() {
            return base.Channel.btnBloodAsync();
        }
        
        public System.Data.DataSet btnAllergic() {
            return base.Channel.btnAllergic();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnAllergicAsync() {
            return base.Channel.btnAllergicAsync();
        }
    }
}
